### ISSUE TITLE
how to create a pdf using another pdf?

### ISSUE THREAD

**Issue by riccardodivirgilio** [jussiniinikoski/wasm-pdf#10]
Hi, I have a printing business I am interested in creating pdf on the client side using other pdf the user might upload or fetch online.
Is it possibile to do that? what I need to do is to create a blank pdf, add one page, embed another pdf page, rotate, scale it (maybe using pdf xobject), embed that page several times in the same page, close the page, open another page and repeat.
Is it possibile to embed another pdf? 

thanks!

**Comment by jussiniinikoski** [comment]
Unfortunately no, we are using exclusively JSON payloads to generate PDF documents.

**Comment by riccardodivirgilio** [comment]
Right but can I use a JSON payload that references pdfs instead of jpegs / pngs?

**Comment by jussiniinikoski** [comment]
I'm afraid not, parsing existing pdfs is not available.

**Comment by riccardodivirgilio** [comment]
thanks!
