### ISSUE TITLE
Links or Anchors support

### ISSUE THREAD

**Issue by AhmedKorim** [jussiniinikoski/wasm-pdf#2]
I 'd love to use this on my next project , currently it fits the requirements,
but if we needed other  block or obj_type like an Anchor for example. will it easy for us to do?
any hints or resources will appreciated

**Comment by jussiniinikoski** [comment]
I guess it shouldn't be too hard to implement hypertext links.  Best advice that I can give you right now is to check out the [official PDF documentation](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf) and work from there. I will probably get back to this project in spring so please let me know if you tackle this!

**Comment by jussiniinikoski** [comment]
Now you can add external links to text.
